Refactor Docker build workflow for tag generation
is it final?

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -13,7 +13,7 @@ on:
 
 
 jobs:
-  prepare_image_tags:
+  pre_build:
     name: Prepare image tags
     runs-on: ubuntu-latest
     outputs:
@@ -23,15 +23,23 @@ jobs:
         id: tagGen
         run: |
          if [ "${{ github.event_name }}" = "release" ]; then
-            echo "tag=Release_${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
+            echo "tag={{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
           else
-            echo "tag=BuildTest_$${{ inputs.version }}" >> $GITHUB_OUTPUT
+            echo "::warning::Build uruchomiony ręcanie"
+            echo "tag=${{ inputs.version }}" >> $GITHUB_OUTPUT
           fi
-      - name: Output Tag
+      - name: Validate Tag
+        id: tagCheck
         run: |
-          echo "output: ${{ steps.tagGen.outputs.tag }}"
+          TAG="${{ steps.tagGen.outputs.tag }}"
+          if [[ -n "$TAG" && "$TAG" =~ ^[0-9.]+$ ]]; then
+            echo "::info::Publikuje z tagiem  ${{ steps.tagGen.outputs.tag }}
+          else
+            echo "::error::Niewłaściwy format taga. poprawny format taha to ##.## gdzie # to cyfra. otrzymano: ${{ steps.tagGen.outputs.tag }}"
+            exit 1
+          fi
   push_to_registry:
-    if: false
+    if: success()
     name: Push Docker image to Docker Hub
     runs-on: ubuntu-latest
     permissions:
@@ -40,11 +48,9 @@ jobs:
       attestations: write
       id-token: write
     steps:
-        
       - name: Check out the repo
         if: false
         uses: actions/checkout@v4
-
       - name: Log in to Docker Hub
         if: false
         uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
@@ -60,4 +66,4 @@ jobs:
           context: .
           file: ./Dockerfile
           push: true
-          tags: krzysztofgornowicz/ggj2026:BuildTest
+          tags: krzysztofgornowicz/ggj2026:${{ needs.pre_build.output.tag }}
